#FUNCIONES CON CARACTERES
#UPPER, LOWER, CONCAT, LENGTH (TAMAÑO), TRIM(LIMPIA ESPACIOS DE IZ Y DER DE CUAL QUIER CADENA)

SELECT UPPER (nombre) FROM usuarios;
SELECT LOWER (nombre) FROM usuarios;

SELECT UPPER(CONCAT(nombre,' ', email)) AS 'Datos Completos' FROM usuarios;

#RETORNA FECHA ACTUAL CURDATE
#DATENAME RETORNA EL NOMBRE DEL DIA DE LA FECHA
#DATEMONTH
#DAYOFWEEK
#DAYOFYEAR DIA DEL AÑO DEL REGISTRO

#SELECT NOMBRE, FECHA_REG, CURDATE() AS 'FECHA ACTUAL' FROM USUARIOS;

#SELECT NOMBRE, DATEDIFF(FECHA_REG, CURDATE()) AS 'DIFERENCIA' FROM USUARIOS;

SELECT DATE_FORMAT(FECHA_REG, '%d-%M-%Y') FROM usuarios;

#/*/*/*/*/*/*/*//*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/*/
#ISSNULL(COLUMNA) PARA DEVOLVER TRUE O FALSE SI ES NULLO
#STRCMP (COLUMAN) COMPROBAR SI DOS CAMPOS SON IGUALES, SI ES DIFERENTE DEVUELVE TRUE DE LO CONTRARIO FALSE
#VERSION () VERIFICAR VERSION DE MYSQL DENTRO DE CONSULTA
#USER() VALIDAR USUARIO DE MYSQL
#DISTINCT MUESTRA SOLO LOS REGISTROS DISTINTOS REGISTRADOS
#DATABASE MUIESTRA NOMBRE DE BBDD
#IFNULL(CAMPO, 'QUE MOSTRA EN CASO DE VACIO') VALIDAR SI UN CAMPO ESTA VACIO
