/*CON ESTAS PRACTICAS HAY QUE COLOCAR SIEMPRE WHERE PARA NO APLICAR A TODOS LOS REGISTROS*/

/*MODIFICAR FILAS DE UN REGISTRO ESPESIFICO */
#UPDATE USUARIOS SET APELLIDOS='Maruca' WHERE ID= 5;

/*ELIMINAR REGISTROS*/
DELETE FROM USUARIOS WHERE EMAIL='MARUCA@GMAIL.COM'; 