#Consulta con una condicion
/*
OPRADORES DE COMPARACION

IGUAL = 
DISTINTO !=
MENOR < O <=
MAYOR > O >=
ENTRE = BETWEEN 
EN = IN
ISNULL(PARAMETROS) ES NULO 
NOT NULL NO ES NULO
LIKE COMO 
NOT LIKE MO ES COMO
*/


#SELECT * FROM USUARIOS WHERE EMAIL = 'TEST2@GMAIL.COM';

#SELECT * FROM USUARIOS;
/*
#USUARIOS QUE SE REGISTRARON EN 2019, MOSTRAR NOMBRE Y USUARIO
*/
#SELECT NOMBRE, APELLIDOS FROM USUARIOS WHERE MONTH(FECHA_REG)=05;
#SELECT NOMBRE, APELLIDOS FROM USUARIOS WHERE YEAR(FECHA_REG)=2019;
/*
#USUARIOS QUE NO SE REGIUSTRARON EN 2019
*/
#SELECT NOMBRE, APELLIDOS FROM USUARIOS WHERE YEAR(FECHA_REG)!=2019;


/*
OPERADORES LOGICOS
O OR
Y AND
NO NOT
*/

/*
COMODINES
CUALQUIER CARACTER : %%
CARACTER DESCONOCIDO : _


*/
/*
LIMIT AND ORDER BY
*/


/*
#EMAIL DE LOS USUARIOS EN QUE APELLIDO TENGA LETRA A
*/
#SELECT EMAIL FROM USUARIOS WHERE APELLIDOS LIKE '%A%' AND PASSWORD = Acceso123;
/*
#SACAR TODOS LOS REGISTROS DE TABLA USUARIOS DE AÑOS PARES
*/

#SELECT * FROM USUARIOS WHERE (YEAR(FECHA_REG)%2=0) AS AÑO ES PAR;

/*SACAR TODOS LOS REGISTROS DE TABLA USUARIO QUE LOS NOMBRES TENGAN MAS DE 5 LETRAS QUE SE 
REGISTRARON ANTES DE 2020 Y MOSTRAR NOMBRE EN MAYUSCULA*/

SELECT UPPER(NOMBRE), APELLIDOS FROM USUARIOS WHERE (LENGTH(NOMBRE)>5) AND YEAR(FECHA_REG)<2020; 

