/*#SON CONSULTAS QUE SE EJECUTAN DENTRO DE OTRA, CONSISTEN EN UITLIZAR LOS RESULTADOS DE 
DE ESTA SUBCONSULTA PARA OPERAR EN LA CONSULTA PRINCIPAL, 
ESTO SE REALIALIZA GRACIAS A LAS LLAVES FORANEAS*/


SELECT * FROM USUARIOS;

INSERT INTI USUARIOS VALUE(NULL,'Marcos', 'Perez', 'admin@gmail.com', 'Acceso123', curdate());

/*Usuarios que tengan entradas. IN PARA CUANDO DEVUELVE VARIOS RESULTADOS*/
 select * from usuarios where id in (select usuarios_id from entradas);

 /*Usuarios que no tiene entradas*/
select * from usuarios where id not in (select usuarios_id from entradas);

/*USUARIOS QUE TENGAN ENTRADAS QUE EN SU TITULO TENGA GTA*/

SELECT NOMBRE, APELLIDOS FROM USUARIOS WHERE ID IN( SELECT USUARIOS_ID FROM ENTRADAS WHERE TITULO LIKE "%GTA%");

/*TODAS LAS ENTRADAS DE LAS CATEGORIAS ACCION USANDO SU NOMBRE*/
SELECT ID, TITULO FROM ENTRADAS WHERE CATEGORIAS_ID IN( SELECT ID FROM CATEGORIAS WHERE NOMBRE 'ACCION');

/*CATEGORIAS CON MAS DE TRES ENTRADAS*/
SELECT COUNT(CATEGORIAS_ID)AS 'CANTIDAD DE LA CATEGORIA', CATEGORIAS_ID FROM ENTRADAS GROUP BY CATEGORIAS_ID;
SELECT NOMBRE FROM CATEGORIAS WHERE ID IN (SELECT CATEGORIAS_ID FROM ENTRADAS GROUP BY CATEGORIAS_ID HAVING COUNT(CATEGORIAS_ID)>=3);


/*SELECCIONAR USUARIOS REGISTRADOS MARTES EN LAS ENTRADAS*/

SELECT * FROM USUARIOS WHERE ID IN (SELECT USUARIOS_ID FROM ENTRADAS WHERE DAYOFFWEEK(FECHA)=3);
