<?php
/*CREAR UN ARRAY CON EL CONTENIDO DE LA SIGUIENTE TABLA
COLUMNA =(INDICE)

ACCION  AVENTURA    DEPORTES
GTA     ASSASING    FIFA 19 
COD     CHASH       PES 19
PUGB    POP         MOTO GP 19

CADA COLUMBA DEBE IR EN UN FICHERO SEPADADO CON INCLUDES

*/ 



?>