/*
COSULTAS ALMACENADAS EN BBDD QUE SE USA COMO TABLA VISTUAL, NO ALMACENA DATOS, USA DATOS DE LAS TABLAS 
ORIGINALES PARA MOSTAR DATOS, DE FORMA QUE SE MANTIENE ACTUALIZADA
*/


CREATE VIEW ENTRADAS_CON_NOMBRES AS 
SELECT E.ID , E.TITULO, U.NOMBRE AS 'AUTOR', C.NOMBRE AS 'CATEGORIAS'
FROM ENTRADAS E
INNER JOIN USUARIOS U ON E.USUARIOS_ID=U.ID
INNER JOIN CATEGORIAS C ON E.CATEGORIAS_ID=C.ID;