/*CONS MULTITABLA SIRVE PAARA CONSULTAR VARIAS TABLAS EN UNA SOLA SENTENCIA, ESTA NO ES LA LA FORMA MAS OPTIMA DE TRABAJAR PERO FUNCIONA
ES MUY LENTO YA QUE RECORRE TODAS LAS FILAS Y TABLAS

*/

/*NOMBRE AUTOR Y NOMBRE DE CATEGORIAS*/

SELECT E.ID , E.TITULO, U.NOMBRE AS 'AUTOR', C.NOMBRE AS 'CATEGORIAS' FROM ENTRADAS E, USUARIOS U, CATEGORIAS C WHERE U.ID = E.USUARIOS_ID AND E.CATEGORIAS_ID=C.ID;

/*NOMBRE DE CATEGORIAS Y ENTRADAS*/

 SELECT C.NOMBRE, COUNT(E.CATEGORIAS_ID) AS 'NO.ENTRADAS' FROM ENTRADAS E , CATEGORIAS C WHERE C.ID=E.CATEGORIAS_ID GROUP BY(CATEGORIAS_ID);



/*MOSTRAR EL MAIL DE LOS USUARIOS Y CUENTAS ENTRADAS*/

SELECT U.NOMBRE,COUNT( E.USUARIOS_ID) AS 'NO.ENTRADAS' FROM ENTRADAS E , USUARIOS U WHERE U.ID=E.USUARIOS_ID GROUP BY(E.USUARIOS_ID);