

/*MISMOS EJERCICIOS CON INNER JOIN

SELECT E.ID , E.TITULO, U.NOMBRE AS 'AUTOR', C.NOMBRE AS 'CATEGORIAS' FROM 
ENTRADAS E, USUARIOS U, CATEGORIAS C WHERE U.ID = E.USUARIOS_ID AND E.CATEGORIAS_ID=C.ID;


*/

SELECT E.ID , E.TITULO, U.NOMBRE AS 'AUTOR', C.NOMBRE AS 'CATEGORIAS'
FROM ENTRADAS E
INNER JOIN USUARIOS U ON E.USUARIOS_ID=U.ID
INNER JOIN CATEGORIAS C ON E.CATEGORIAS_ID=C.ID;




/*
LEFT JOIN PARA QUE MUESTRE LOS MATCH AUN SI NO COINCIDENm MATENER TODAS LAS FILAS DE LA TABLA IZQUIERDA
AUN ESTEN EN NULL O TODO LO DE LA DERECHA QUE ESTE EN LA COINCIDENCIA
 SELECT C.NOMBRE, COUNT(E.CATEGORIAS_ID) AS 'NO.ENTRADAS' 
 FROM ENTRADAS E , CATEGORIAS C WHERE C.ID=E.CATEGORIAS_ID GROUP BY(CATEGORIAS_ID);
*/


 SELECT C.NOMBRE, COUNT(E.CATEGORIAS_ID) AS 'NO.ENTRADAS' 
 FROM CATEGORIAS C 
 LEFT  JOIN ENTRADAS E ON C.ID=E.CATEGORIAS_ID GROUP BY(CATEGORIAS_ID);


/*
RIGHT JOIN TODO LO CONTRARIO AL LEFT JOIN

*/

 SELECT C.NOMBRE, COUNT(E.CATEGORIAS_ID) AS 'NO.ENTRADAS' 
 FROM CATEGORIAS C 
 RIGHT  JOIN ENTRADAS E ON C.ID=E.CATEGORIAS_ID GROUP BY(CATEGORIAS_ID);


 