/*RELLENANDO TABLAS*/

/*CIUDAD*/

INSERT INTO CIUDAD VALUES(NULL, 'SANTO DOMINGO' );
INSERT INTO CIUDAD VALUES(NULL, 'SANTIAGO' );
INSERT INTO CIUDAD VALUES(NULL, 'MIAMI' );
/*CARGO*/
INSERT INTO CARGO VALUES(NULL, 'RESPONSABLE TIENDA' );
INSERT INTO CARGO VALUES(NULL, 'VENDEDOR' );
INSERT INTO CARGO VALUES(NULL, 'GERENTE VENTAS' );
INSERT INTO CARGO VALUES(NULL, 'SUPERVISOR VENTAS' );
/*MARCA*/
INSERT INTO MARCA VALUES(NULL, 'TOYOTA' );
INSERT INTO MARCA VALUES(NULL, 'FORD' );
INSERT INTO MARCA VALUES(NULL, 'NISSAN' );
INSERT INTO MARCA VALUES(NULL, 'HONDA' );

/*MODELO*/
INSERT INTO MODELO VALUES(NULL, 'VIZT' );
INSERT INTO MODELO VALUES(NULL, 'FOCUS' );
INSERT INTO MODELO VALUES(NULL, 'SENTRA' );
INSERT INTO MODELO VALUES(NULL, 'FIT' );

/*GRUPO*/
INSERT INTO GRUPO VALUES(NULL, 'GRUPO A', 1 );
INSERT INTO GRUPO VALUES(NULL, 'GRUPO B', 2 );
INSERT INTO GRUPO VALUES(NULL, 'GRUPO C', 3 );

/*AUTOS*/

INSERT INTO AUTOS VALUES(NULL, 1, 1, 20 );
INSERT INTO AUTOS VALUES(NULL, 2, 2, 30 );
INSERT INTO AUTOS VALUES(NULL, 3, 3, 40 );
INSERT INTO AUTOS VALUES(NULL, 4, 4, 10 );


/*VENDEDORES*/
INSERT INTO VENDEDORRES VALUES(NULL, 'ANGEL', 'GUERRERO', 1, 1, 1, CURDATE(), 50000, 4  );
INSERT INTO VENDEDORES VALUES(NULL, 'PEDRO', 'PEREZ', 2, 4, 1, CURDATE(), 30000, 3  );
INSERT INTO VENDEDORES VALUES(NULL, 'MARIO', 'JIMENEZ', 1, 6, 1, CURDATE(), 60000, 5  );

/*CLIENTES*/
INSERT INTO CLIENTES VALUES(NULL, 1 ,'MARINO P', 1, 114000, CURDATE() );
INSERT INTO CLIENTES VALUES(NULL, 4 ,'MAYELLA CARS', 2, 3504000, CURDATE() );
INSERT INTO CLIENTES VALUES(NULL, 1 ,'JUANA PEREZ', 1, 124000, CURDATE() );

/*COMPRAS_ENCARGOS*/

INSERT INTO COMPRAS_ENCARGOS VALUES(NULL, 1 ,1, 3, CURDATE() );

INSERT INTO COMPRAS_ENCARGOS VALUES(NULL, 4 ,3, 3, CURDATE() );


INSERT INTO COMPRAS_ENCARGOS VALUES(NULL, 3 ,1, 3, CURDATE() );


INSERT INTO COMPRAS_ENCARGOS VALUES(NULL, 1 ,1, 3, CURDATE() );
